version: '3.9'

services:

  db:
    image: mysql:8.0.34
    container_name: mysql-container
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_DB
    ports:
      - "6666:3306"
    networks:
      - productapp-network
  product-app:
    image: smeashwani/product:dev
    container_name: product-app.com
    ports: 
      - "8881:8888"
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on: 
      - db
    networks:
      - productapp-network
networks:
  productapp-network:
    driver: bridge